### ISSUE TITLE
Show finishes, resets player, but the "Play" icon is still showing

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/litestream#177] opened 2024-04-28 19:41 UTC
I was unable to reproduce this, but it happened while I was out, after playing 3/28/88 completely. Here is the serial output:
```
Playing -- Read 3555396/3590869 (99%) of track 23/23 InBuffer: 100% OutBuffer: 99%
Track read end
Finished reading playlist
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 28% OutBuffer: 99%
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
...
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 0% OutBuffer: 0%
2$JiB���r"���+�I��r"��!��)ˋ �K��ad 3�N�6��5�:  ~/projects/litestream/timemachine ; 
```

When I played it again, no problem. The output was:

```
Playing -- Read 3423623/3590869 (95%) of track 23/23 InBuffer: 100% OutBuffer: 99%
Playing -- Read 3580551/3590869 (100%) of track 23/23 InBuffer: 100% OutBuffer: 99%
Track read end
Finished reading playlist
Playing -- Read 3590869/3590869 (100%) of track 23/23 InBuffer: 15% OutBuffer: 91%
Track 23 decode end
Finished decoding playlist
Track play end
Finished playing playlist
Stopped --
Stopped --
```

**Comment by ma261065** [comment] 2024-04-29 05:34
I just got the same behaviour on that show:

```
Playing -- Read 3076935/3590869 (86%) of track 23/23 InBuffer: 100% OutBuffer: 99%
Playing -- Read 3218083/3590869 (90%) of track 23/23 InBuffer: 100% OutBuffer: 99%
Playing -- Read 3356785/3590869 (93%) of track 23/23 InBuffer: 100% OutBuffer: 99%
Playing -- Read 3502155/3590869 (98%) of track 23/23 InBuffer: 100% OutBuffer: 99%
Track read end
Finished reading playlist
Playlist not started
Playlist not started
Playlist not started
Playlist not started
```

I am still running the older version with the `playlist_started` variable so the output is expected to be different, but note that we got the "Finished reading playlist" message, but no "Track 23 decode end", "Finished decoding playlist" messages.

I also note that at the beginning of the set it had the following:
```
Selected date string  3-28-1988
Track read start
Getting /download/gd1988-03-28.sbd.miller.91233.sbeok.flac16/gd88-03-28d1t01.ogg from archive.org, Port:443, Offset 0
Select UP
Track read end
Track read start
Track 0 decode start
Skipping 0 bytes
Decoder Start success. Sync word at 0
Not an audio track
Playlist not started
Playlist not started
Track read start
Getting /download/gd1988-03-28.sbd.miller.91233.sbeok.flac16/gd88-03-28d1t02.ogg from archive.org, Port:443, Offset 0
Getting /download/gd1988-03-28.sbd.miller.91233.sbeok.flac16/gd88-03-28d1t02.ogg from archive.org, Port:443, Offset 0
Track 1 decode start
Skipping 0 bytes
Decoder Start success. Sync word at 0
Track play start
Playing -- Read 32145/7098623 (0%) of track 1/23 InBuffer: 2% OutBuffer: 5%
Playing -- Read 380250/7098623 (5%) of track 1/23 InBuffer: 100% OutBuffer: 98%
```

For some reason we got the "Not an Audio Track" message and then two reads of the same track. I think all this has messed up the trackinfo variable which keeps track of track length etc.

Need to debug why we got "Not an audio track", and why it didn't happen the second time on your test above.

**Comment by ma261065** [comment] 2024-04-29 05:45
So it seems that `https://archive.org/6/items/gd1988-03-28.sbd.miller.91233.sbeok.flac16/gd88-03-28d1t01.ogg` will also not play in the browser, and hexedit shows that it is indeed an Ogg/Theora file so the "Not an audio track" message is correct.

Now to debug why the next track got requested twice as I think that is the root cause of the problem.

**Comment by ma261065** [comment] 2024-04-29 09:32
The next track getting read twice is a race condition. Because when we hit the unplayable file we may or may not have already started reading the next track. So I need to work out some better logic to handle that.

**Comment by ma261065** [comment] 2024-04-29 13:07
Fixed by https://github.com/eichblatt/litestream/commit/36eb7919eaf8eb9dfb210f138a4963dc524ae023

**Closed by ma261065** 2024-04-29 13:07 UTC
