### ISSUE TITLE
Phish 9/1/23 set 2

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/litestream#89] opened 2024-01-17 02:19 UTC
Drew reports having tracks in set 2 of Phish, 9/1/23 play for a second or so every minute. 

On playing the set again, there were no problems.

**Comment by deichblatt** [comment] 2024-01-25 23:06
I have had this problem again, with Phish 10/31/98, set 3. I am not sure how to duplicate the issue yet as it seems to happen randomly (for example, set 1 > set 2 worked fine). Temporary solution is to go back one track, and then forward again and it seems to resolve the current issue.

**Comment by eichblatt** [comment] 2024-01-26 17:15
To reproduce this problem:

-  Select Phish 12/31/99
-  FFwd to the set break. 
-  Play the set break.
- When the next track (Meatstick) starts playing, it drops out after a few seconds. After a minute or so, it picks back up.

The terminal output when this happens is
```
Playing -- Read 162163/10260788 (2%) of track 15/51 InBuffer: 100% OutBuffer: 94%
Playing -- Read 163545/10260788 (2%) of track 15/51 InBuffer: 100% OutBuffer: 99%
Track 14 decode end
Track 15 decode start
ID3 tag size: 1003
Skipping 1003 bytes
Track play end
Track play start
Playing -- Read 165802/10260788 (2%) of track 15/51 InBuffer: 0% OutBuffer: 0%
Playing -- Read 165802/10260788 (2%) of track 15/51 InBuffer: 0% OutBuffer: 0%
Playing -- Read 165802/10260788 (2%) of track 15/51 InBuffer: 0% OutBuffer: 0%
Playing -- Read 165802/10260788 (2%) of track 15/51 InBuffer: 0% OutBuffer: 0%
Playing -- Read 165802/10260788 (2%) of track 15/51 InBuffer: 0% OutBuffer: 0%
Playing -- Read 165802/10260788 (2%) of track 15/51 InBuffer: 0% OutBuffer: 0%
Peer close
Socket Exception: Peer closed socket  Restarting track at offset 407471
Playing -- Read 791961/10260788 (8%) of track 15/51 InBuffer: 100% OutBuffer: 100%
```

**Comment by eichblatt** [comment] 2024-01-27 16:08
I have added a PHISH HACK to the audioplayer.py, which "fixes" this problem. See https://github.com/eichblatt/litestream/commit/e9b9a78bb292a69ae29bd628c8447be4d8d4a1ed

**Comment by ma261065** [comment] 2024-04-18 08:13
This was caused by the TCP stack misbehaving. Wireshark showed that a while into the setbreak track that TCP would suddenly stop ACKing packets from archive.org. This caused a flood of retries that it never recovered from until the connection eventually got closed.

After much experimentation, landed on a new set of TCP parameters that fixed the issue.

Note - it will still get a "Socket closed by peer" exception during the setbreak, but it will now recover. This is "normal', and is caused by us reading the data so slowly during a setbreak (which comes from the buffer, so doesn't cause any TCP traffic)  that the other end thinks we've given up and closes the socket. The reason we read so slowly is that silence compresses REALLY WELL, so it needs very little data to play a long silence file.

**Closed by ma261065** 2024-04-18 08:13 UTC
